server:
  port: 8090
  servlet:
    context-path: /demo-api
spring:
  datasource:
    url: jdbc:h2:mem:employee-db
    driverClassName: org.h2.Driver
    username: asa
    password: asa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect